# Generated by Django 3.2.7 on 2021-10-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.IntegerField(default=150, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
